### ISSUE TITLE
Unity plugin?

### ISSUE THREAD

**Issue by yosun** [deurell/roomscanner#4]
Hey, found your blog post... and the mention of Unity... it seems that Unity officially will not be adding this to their ARFoundation/ARKit. Curious about whether you might make it a Unity plugin for 7 million Unity devs out there! 

https://deurell.github.io/posts/roomplan-swiftui/

**Comment by deurell** [comment]
A great idea limited only by my available time. Maybe some time in the future. Thanks for the suggestion.
